# Generated by Django 5.1.6 on 2025-03-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='คำศัพท์')),
                ('pronunciation', models.CharField(max_length=100, verbose_name='คำอ่าน')),
                ('thai_translation', models.CharField(max_length=100, verbose_name='คำแปลภาษาไทย')),
                ('english_translation', models.CharField(max_length=100, verbose_name='คำแปลภาษาอังกฤษ')),
                ('category', models.CharField(choices=[('Noun', 'Noun'), ('Pronoun', 'Pronoun'), ('Verb', 'Verb'), ('Adverb', 'Adverb'), ('Adjective', 'Adjective'), ('Conjunction', 'Conjunction'), ('Phrase', 'Phrase'), ('Preposition', 'Preposition'), ('Time', 'Time'), ('Clothes', 'Clothes'), ('Plants', 'Plants'), ('Animals', 'Animals'), ('Utensils', 'Utensils')], max_length=20, verbose_name='หมวดหมู่')),
                ('sound_file', models.FileField(blank=True, null=True, upload_to='vocabulary_sounds/', verbose_name='ไฟล์เสียง')),
            ],
            options={
                'verbose_name': 'คำศัพท์',
                'verbose_name_plural': 'คำศัพท์',
                'ordering': ['category', 'word'],
            },
        ),
    ]
